#spring:
 # datasource:
  #  url: jdbc:mysql://localhost:3306/my_db
   # username: "admin"
    #password: "my_password"
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari:
     # maximum-pool-size: 10

  #jpa:
   # properties:
    #  hibernate:
     #   dialect: org.hibernate.dialect.MySQLDialect
    #hibernate:
     # ddl-auto: update
    #show-sql: true
#logging:
 # level:
  #  org.hibernate.SQL: debug